package com.learn.majiang.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parentId
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentor
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    private String commentor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmtCreate
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    private Long gmtcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmtModified
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    private Long gmtmodified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.likeCount
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    private Long likecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parentId
     *
     * @return the value of comment.parentId
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parentId
     *
     * @param parentid the value for comment.parentId
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentor
     *
     * @return the value of comment.commentor
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public String getCommentor() {
        return commentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentor
     *
     * @param commentor the value for comment.commentor
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public void setCommentor(String commentor) {
        this.commentor = commentor == null ? null : commentor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmtCreate
     *
     * @return the value of comment.gmtCreate
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public Long getGmtcreate() {
        return gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmtCreate
     *
     * @param gmtcreate the value for comment.gmtCreate
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public void setGmtcreate(Long gmtcreate) {
        this.gmtcreate = gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmtModified
     *
     * @return the value of comment.gmtModified
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public Long getGmtmodified() {
        return gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmtModified
     *
     * @param gmtmodified the value for comment.gmtModified
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public void setGmtmodified(Long gmtmodified) {
        this.gmtmodified = gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.likeCount
     *
     * @return the value of comment.likeCount
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public Long getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.likeCount
     *
     * @param likecount the value for comment.likeCount
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public void setLikecount(Long likecount) {
        this.likecount = likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Tue Sep 03 12:38:04 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}